---
- name: "Reset Password" 
  hosts: all
  become: true
  vars:
  - user_name : 'inframycompanytec'
  - pass_word : 'minha_senha123*'

  tasks:
    - name: "Reset Password"
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ pass_word | password_hash('sha512', 'mysalt') }}"

