---
- name: "Delete user from group" 
  hosts: all
  become: true
  vars:
  - user_name: 'simycompanytec'
  - group_name_redhat: 'wheel'
  - group_name_debian: 'sudo'

  tasks:
    - name: "Enable user Red Hat Like"
      shell: "gpasswd -d {{ user_name }} {{ group_name_debian }}"
      when: (ansible_facts['os_family'] == "Debian")

    - name: "Enable user Debian Like"
      shell: "gpasswd -d {{ user_name }} {{ group_name_redhat }}"
      when: (ansible_facts['os_family'] == "RedHat")

