---
- name: Install Open VM Tools
  hosts: all
  become: yes
  tasks:

    - name: Install open-vm-tools on Red Hat like systems
      yum: 
        name: open-vm-tools
        state: present
      when: (ansible_facts['os_family'] == "RedHat")

    - name: Install open-vm-tools on Debian systems
      apt:
        name: open-vm-tools
        state: present
      when: (ansible_facts['os_family'] == "Debian")

    - name: Start/Enable servide
      service: 
        name: vmtoolsd
        state: started
        enabled: yes
