---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: (ansible_facts['os_family'] == "Debian")

- name: Install ldap integration dependencies on Red Hat like systems
  yum:
    name: "{{ yum_install }}"
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Install ldap integration dependencies on Debian systems
  apt:
    name: "{{ apt_install }}"
    state: present
  when: (ansible_facts['os_family'] == "Debian")
