---
- name: Create certificate directory if it does not exist
  ansible.builtin.file:
    path: /etc/pki/tls/certs/
    state: directory
    mode: '0755'

- name: Transfer ldap CA certificate to the server
  ansible.builtin.copy:
    src: ./ca-mycompany.pem
    dest: /etc/pki/tls/certs/ca-mycompany.pem
    owner: root
    group: root
    mode: '0600'

- name: Transfer custom sssd.conf file to the server
  ansible.builtin.copy:
    src: ./sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
