---
- name: Get VMs info
  hosts: localhost
  become: false
  gather_facts: false

  pre_tasks:
    - include_vars: vars_ntnx.yml

  tasks:
    - name: Retrieve VM info
      vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: "{{ datacenter_name }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        #vm_name: "CJBLVAIRFLOW-QA"
      register: vm_info


    - debug:
        msg: "{{ item.tags }}"
      with_items:
        - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
      vars:
        query: "[?guest_name=='CJBLVAIRFLOW-QA']"
