---
- name: Stop Vsphere Virtual Machine
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: Guest Shutdown
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: "/{{ datacenter_name }}"
        validate_certs: "{{ vcenter_validate_certs }}" 
        name: "{{ item }}"
        state: shutdown-guest
        state_change_timeout: 120
      register: shutdown
      ignore_errors: true
      loop: "{{ guest_name }}"

    - name: Guest Poweroff
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ item }}"
        state: powered-off 
      when: item.failed
      loop: "{{ shutdown.results }}"
