---
- name: Set Kubelet service to work with VSphere Cloud Provider.
  lineinfile:
    path: /lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: "^ExecStart=/usr/bin/kubelet"
    line: "ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS --cloud-provider=vsphere --cloud-config=/etc/kubernetes/.vsphere.conf"
    state: present
    backup: false

- name: Copy VSphere Cloud Provider config file to node.
  template:
    dest: /etc/kubernetes/.vsphere.conf
    src: vsphere.conf.j2

- name: systemctl daemon-reload
  command: systemctl daemon-reload
