---
- name: Copy Init config file to Controlplane.  
  template:
    dest: /etc/kubernetes/init.yaml
    src: init.yaml.j2
  when: inventory_hostname in groups['controlplane']
  tags:
    - initfile 

- name: Deploy Kubernetes Controlplane
  shell: kubeadm init --config /etc/kubernetes/init.yaml
  become: yes
  when: inventory_hostname in groups['controlplane']

- name: Create .kube directory
  file:
    path: "/root/.kube"
    state: directory
    owner: root
    mode: 0755
  tags:
    - directory
  when: inventory_hostname in groups['controlplane']

- name: Create .kube directory
  file:
    path: "/home/{{ kubectl_user }}/.kube"
    state: directory
    owner: "{{ kubectl_user }}"
    mode: 0755
  tags:
    - directory
  when: inventory_hostname in groups['controlplane']

- name: Copy admin.conf to user kube config to root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  tags:
    - directory
  when: inventory_hostname in groups['controlplane']

- name: Copy admin.conf to user kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ kubectl_user }}/.kube/config"
    owner: "{{ kubectl_user }}"
    remote_src: yes
  tags:
    - directory
  when: inventory_hostname in groups['controlplane']
